skycoin/cxo

cmd/bbsClient/bbsClient.go, cmd/bbsClient/rpc_client.go, cmd/bbsServer/bbsServer.go
Implemented simple bbs server/client with simple hello world CLI over RPC.
=> Implemented simple bbs server/client.

node/config.go, node/config_test.go, node/connection.go, node/connection_test.go, node/events.go, node/incoming.go, node/message.go, node/network_test.go, node/node.go, node/node_test.go, node/outgoing.go, node/ping.go, node/route_test.go
+ add user  data feature to cxo/node
+ improve test cases
+ improve closing of node
=> add user-data feature to cxo/node

cmd/cli/README.md, cmd/cli/cli.go, cmd/cxod/cxod.go, data/data.go, data/data_test.go, node/README.md, node/node.go, node/rpc.go, node/rpc/README.md, node/rpc/client/client.go, node/rpc/server/server.go
+ move RPC server from node/ to node/rpc/server (lib)
+ move RPC client from cmd/cli to node/rpc/client (lib)
+ refactor cmd/cxod
+ refactor cmd/cli
+ add ability to terminate node using RPC
=> node/ RPC refactoring

skyobject/container.go, skyobject/dynamic.go, skyobject/traverse.go, tests/skyobjectsQuickstart.go
+ dynamic references
+ comments
=> Fix and enalble "dynamic reference" feature

cmd/cli/cli.go, node/messages.go, node/node.go, node/node_test.go, node/rpc.go, rpc/client/client.go, rpc/comm/comm.go, rpc/server/server.go, skyobject/container.go, skyobject/container_test.go, skyobject/references.go, skyobject/references_test.go, skyobject/root.go, skyobject/root_test.go, skyobject/schema.go, skyobject/traverse.go, skyobject/traverse_test.go, skyobject/want.go, skyobject/want_test.go, tests/skyobjectsQuickstart.go
Fix misbehavior of skyobject encoding that fails sign and verify its signature.
=> fix skyobject sign, encode and decode

cmd/cli/cli.go, node/node.go, node/node_test.go, node/rpc.go, readme.md, rpc/client/client.go, rpc/comm/comm.go, rpc/server/server.go, skyobject/container.go, skyobject/container_test.go, skyobject/root.go, skyobject/root_test.go, skyobject/traverse.go, skyobject/traverse_test.go, skyobject/want.go, skyobject/want_test.go, tests/skyobjectsQuickstart.go
+ move some methods of skyobject.Root to skyobject.Container
+ remade test/skyobjectQuickStart
+ remade readme documentation
+ add feature to inject an object to a root using hash reference of the object
=> skyobject, documentation, inject

node/messages.go, node/node.go, node/rpc.go
=> fix up node replication adopting previous algoritm to many rot objects

cmd/cli/cli.go, cmd/test/run.sh, data/data.go, node/rpc.go, rpc/comm/comm.go
add missing `defer` before `d.RUnlock()` in data/
=> data/ fix stupid-race-lock-bug-type-mistake

cmd/test/README.md, cmd/test/run.sh, cmd/test/test.go, node/gnet/config.go, node/gnet/conn.go, node/gnet/pool.go, node/gnet/pool_test.go, node/node.go
+ fixing PING/PONG messages sending
+ fix cmd/test/run.sh to kill all processes when  the script is done
=> node/gnet fix pings/pongs, cmd/test fix killing

node/client.go, node/rootwalker.go, node/rootwalker_test.go
Made it easier to update nested objects in cxo.
=> Added RootWalker

node/client.go, node/config.go, skyobject/container.go
node/
+ add `(*Client).IsConnected() bool` method
+ add `OnConenct` and `OnDisconnect` callbacks to `ClientConfig`
=> node/ add (*Client).IsConnected method

cmd/cxod/cxod.go, node/config.go, node/server.go
Added blockdb opening and closing. 
As well as ability to randomise db file name and delete it on exit.
=> Add BlockDB initialisation on server start

node/rootwalker.go, node/rootwalker_test.go
Implemented `GetFromRefsField`, `GetFromRefField`, `GetFromDynamicField`, `ReplaceInRefsField` and `RemoveInRefsField` and corresponding tests.
=> Add more methods to the RootWalker

node/client.go
+ removed `IsConnected() bool` method
+ introduced `Conn() *gnet.Conn` method
=> node/ Client: removed IsConnected, introduced Conn methods

node/client.go, node/client_test.go
+ add `(*Cleint).FeedsOfServer() (feeds []cipher.PubKey)` method
=> node/ Client: add FeedsOfServer method

node/CHANGELOG.md, node/README.md, node/config.go, node/gnet/conn.go, node/gnet/pool_test.go, node/node.go, node/node_test.go
+ fix background subscribing if SubscribeResponse fails by timeout
+ add OnDialFilter
+ add OnDialFilter to NodeConfig by default
+ add CHANGELOG.md and move TODOs to the CHANGELOG.md
=> node/ fixes for SusbscribeResponse + add OnDialFilter

.gitignore, cmd/cxocli/README.md, node/README.md, node/example_test.go, node/node.go, node/node_examples_test.go
+ add examples for methods of node.Node
+ add package example for node
=> node/ add examples

data/CHANGELOG.md, data/data.go, data/data_test.go, data/drive.go, data/memory.go, node/CHANGELOG.md, node/node.go, skyobject/CHANGELOG.md, skyobject/container.go, skyobject/container_test.go, skyobject/root.go, skyobject/root_test.go
+ added `RangeFeedDelete` method
+ added `RamoveNonFullRoots` method
+ remove all non-full root objects and clean up database during shutdown
=> node/ remove non-full roots during shutdown

node/event.go, skyobject/container.go
Temporary stub for `skyobject.Container.DelFeed`.
=> node/ DelFeed fix unsubscribing; skyobject/ stub for DelFeed

data/idxdb/drive.go, data/idxdb/idxdb.go, data/idxdb/idxdb_test.go, data/idxdb/roots_test.go, skyobject/root.go, skyobject/unpack.go
The `LastFull` method was returning Root without Sig and LastFull.
=> skyobject/ fix `Container.LastFull`

README.md, cxoutils/cxoutils.go, data/cxds.go, data/cxds/cxds.go, data/cxds/drive.go, data/cxds/memory.go, data/data.go, data/idxdb.go, data/idxdb/drive.go, intro/README.md, intro/cleanup/cleanup.go, intro/discovery/README.md, intro/discovery/exchange/ca/ca.go, intro/discovery/exchange/cb/cb.go, intro/discovery/through/README.md, intro/discovery/through/server/server.go, intro/preview/peer/peer.go, intro/preview/seed/seed.go, intro/send_receive/README.md, intro/send_receive/dst/dst.go, intro/send_receive/src/src.go, intro/skybrief/main.go, node/config.go, skyobject/cache.go, skyobject/fill.go
new syntax errors where found and fixed
respectivaly.
=> doc syntax error fixed

README-CN.md, README.md
=> Chinese doc.
